Update NewHelloWorlds.yml

diff --git a/.github/workflows/NewHelloWorlds.yml b/.github/workflows/NewHelloWorlds.yml
--- a/.github/workflows/NewHelloWorlds.yml
+++ b/.github/workflows/NewHelloWorlds.yml
@@ -63,6 +63,9 @@ jobs:
           exit 1
           fi
 
+         # Set as step output
+          echo "token=$token" >> $GITHUB_OUTPUT
+
       # Step 5 Execute Test Set from UiPath Test manager
       - name: Trigger_Test_Set_Execution
         run: |
@@ -78,7 +81,10 @@ jobs:
           
           # Extract execution ID
           execution_id=$(echo "$response" | jq -r '.id')
-          echo "Execution ID: $execution_id"
+          if [ "$execution_id" = "null" ] || [ -z "$execution_id" ]; then
+           echo "Failed to start execution"
+          exit 1
+          fi"
           
           # Set output for later steps
           echo "execution_id=$execution_id" >> $GITHUB_OUTPUT
